// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbEkM9EqGfoy3sfRRDiinTXMQJAtGHqFM',
    appId: '1:1059268687688:web:ea1f906e19b9e85556e57d',
    messagingSenderId: '1059268687688',
    projectId: 'trademarketplaceimg',
    authDomain: 'trademarketplaceimg.firebaseapp.com',
    storageBucket: 'trademarketplaceimg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3pXaqokhxTskeuHieVjWWxNt2hrvb_bs',
    appId: '1:1059268687688:android:46a449f8cbd871c956e57d',
    messagingSenderId: '1059268687688',
    projectId: 'trademarketplaceimg',
    storageBucket: 'trademarketplaceimg.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOJuufN9EAHOBwBHpW8QdEv_W_0GghqB8',
    appId: '1:1059268687688:ios:6414348a0dfc20da56e57d',
    messagingSenderId: '1059268687688',
    projectId: 'trademarketplaceimg',
    storageBucket: 'trademarketplaceimg.firebasestorage.app',
    iosBundleId: 'com.example.agoraofolymus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbEkM9EqGfoy3sfRRDiinTXMQJAtGHqFM',
    appId: '1:1059268687688:web:ffe75f58dfde91aa56e57d',
    messagingSenderId: '1059268687688',
    projectId: 'trademarketplaceimg',
    authDomain: 'trademarketplaceimg.firebaseapp.com',
    storageBucket: 'trademarketplaceimg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOJuufN9EAHOBwBHpW8QdEv_W_0GghqB8',
    appId: '1:1059268687688:ios:6414348a0dfc20da56e57d',
    messagingSenderId: '1059268687688',
    projectId: 'trademarketplaceimg',
    storageBucket: 'trademarketplaceimg.firebasestorage.app',
    iosBundleId: 'com.example.agoraofolymus',
  );

}